In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('cars.csv')

In [3]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [4]:
df.shape

(8128, 5)

In [5]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [6]:
df['brand'].nunique()

32

# 1. One Hot Encoding using pandas

In [7]:
pd.get_dummies(df,columns=['fuel','owner'], dtype=int)

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,0,1,0,0,1,0,0,0,0
1,Skoda,120000,370000,0,1,0,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,0,0,1
3,Hyundai,127000,225000,0,1,0,0,1,0,0,0,0
4,Maruti,120000,130000,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,1,1,0,0,0,0
8124,Hyundai,119000,135000,0,1,0,0,0,1,0,0,0
8125,Maruti,120000,382000,0,1,0,0,1,0,0,0,0
8126,Tata,25000,290000,0,1,0,0,1,0,0,0,0
8127,Tata,25000,290000,0,1,0,0,1,0,0,0,0

# 2. K-1 OneHotEncoding

In [8]:
pd.get_dummies(df,columns=['fuel','owner'], drop_first=True, dtype=int)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1,0,0,0,0,0,0
1,Skoda,120000,370000,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,0
4,Maruti,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,1,0,0,0,0
8124,Hyundai,119000,135000,1,0,0,1,0,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,0

# 3. One hot Encoding using Sklearn

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1], test_size=0.2, random_state=True)

In [10]:
X_train

        brand  km_driven    fuel         owner
1939    Honda     100000  Diesel  Second Owner
5455   Maruti     120000  Diesel  Second Owner
7079  Renault     100000  Diesel  Second Owner
2000    Honda      80000  Petrol  Second Owner
1578    Honda      56494  Petrol   First Owner
...       ...        ...     ...           ...
7935   Maruti     100000  Petrol   Third Owner
5192  Hyundai     152000  Diesel   First Owner
3980  Hyundai      70000  Petrol   First Owner
235    Maruti     110000  Diesel  Second Owner
5157   Maruti      65755  Petrol   First Owner

[6502 rows x 4 columns]

In [11]:
X_test

         brand  km_driven    fuel        owner
1392  Mahindra      80000  Diesel  First Owner
7778      Tata      45000  Diesel  First Owner
3727   Hyundai      60000  Diesel  First Owner
6630      Tata      15000  Petrol  First Owner
103     Maruti     100000  Petrol  Third Owner
...        ...        ...     ...          ...
3697    Maruti     120000  Diesel  First Owner
3001   Hyundai     110000  Diesel  Third Owner
94      Maruti      55500  Petrol  First Owner
4535    Maruti      15000  Diesel  First Owner
1610    Maruti      25000  Petrol  First Owner

[1626 rows x 4 columns]

In [12]:
from sklearn.preprocessing import OneHotEncoder

In [13]:
ohe = OneHotEncoder(sparse_output=False, drop='first', dtype=np.int32)

In [14]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])

In [15]:
X_test_new = ohe.transform(X_test[['fuel','owner']])

In [16]:
X_train_new

array([[1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]], shape=(6502, 7), dtype=int32)

In [17]:
np.hstack((X_train[['brand','km_driven']].values, X_train_new))

array([['Honda', 100000, 1, ..., 1, 0, 0],
       ['Maruti', 120000, 1, ..., 1, 0, 0],
       ['Renault', 100000, 1, ..., 1, 0, 0],
       ...,
       ['Hyundai', 70000, 0, ..., 0, 0, 0],
       ['Maruti', 110000, 1, ..., 1, 0, 0],
       ['Maruti', 65755, 0, ..., 0, 0, 0]], shape=(6502, 9), dtype=object)

# One hot encoding with Top categories

In [18]:
count = df['brand'].value_counts()

In [19]:
df['brand'].nunique()
threshold = 100

In [20]:
repl = count[count<=threshold].index

In [21]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon'), dtype=int).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
4656,0,0,0,0,0,0,1,0,0,0,0,0,0
2021,0,0,0,0,0,0,1,0,0,0,0,0,0
5913,0,0,0,0,0,0,0,0,0,0,1,0,0
7664,0,0,0,0,1,0,0,0,0,0,0,0,0
975,0,0,0,0,1,0,0,0,0,0,0,0,0